openapi: 3.0.3
info:
  title: FastAPI Todo Backend Service
  description: REST API for managing user tasks with JWT authentication and user-scoped operations
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /tasks:
    get:
      summary: List user's tasks
      description: Retrieve all tasks belonging to the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{task_id}:
    get:
      summary: Get task details
      description: Retrieve details of a specific task owned by the user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Task details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have access to this task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a task
      description: Update all details of a specific task owned by the user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have access to this task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a task
      description: Delete a specific task owned by the user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have access to this task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/{task_id}/toggle:
    patch:
      summary: Toggle task completion
      description: Toggle the completion status of a specific task owned by the user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have access to this task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TaskResponse:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          example: 123
          description: Unique identifier for the task
        user_id:
          type: string
          example: "user-uuid-string"
          description: ID of the user who owns this task
        title:
          type: string
          example: "Complete project proposal"
          description: Brief title of the task
          maxLength: 255
        description:
          type: string
          example: "Finish the technical specifications document"
          description: Detailed description of the task
          maxLength: 1000
          nullable: true
        completed:
          type: boolean
          example: false
          description: Whether the task is completed
        created_at:
          type: string
          format: date-time
          example: "2026-01-09T10:30:00Z"
          description: Timestamp when the task was created
        updated_at:
          type: string
          format: date-time
          example: "2026-01-09T10:30:00Z"
          description: Timestamp when the task was last updated

    TaskCreateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Complete project proposal"
          description: Brief title of the task
          minLength: 1
          maxLength: 255
        description:
          type: string
          example: "Finish the technical specifications document"
          description: Detailed description of the task
          maxLength: 1000
        completed:
          type: boolean
          example: false
          description: Initial completion status of the task

    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          example: "Complete project proposal"
          description: Updated title of the task
          minLength: 1
          maxLength: 255
        description:
          type: string
          example: "Finish the technical specifications document"
          description: Updated description of the task
          maxLength: 1000
        completed:
          type: boolean
          example: true
          description: Updated completion status of the task

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          example: "Task not found"
          description: Detailed error message